image: otaviog/ubuntu-xenial-fiontb

before_script:
  - python3 -m venv venv
  - source venv/bin/activate
  - pip3 install .

cache:
  paths:
    - venv

stages:
  - deploy


pages:
  stage: deploy
  script:
    - pip3 install -r requirements-dev.txt
  artifacts:
    paths:
      - public
  only:
    - master
