channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cmake>=3.14.0
  - cudatoolkit>=10.1.0
  - cudnn
  - eigen>=3.3.7
  - numpy>=1.18.1
  - pytorch>=1.2.0
  - opencv>=3.4.2
  - scipy>=1.4.1
  - pykdtree>=1.3.1
  - matplotlib>=3.1.3
  - pip:
      numpy-quaternion>=1.81.1
      numba>=0.48.0
      natsort>=7.0.0
